-- Crea las secuencias usadas por el backend si no existen.
-- Arranca cada secuencia en MAX(PK)+1 cuando la tabla existe.
--
-- Importante:
-- No se crea un PROCEDURE guardado porque Oracle puede dar ORA-01031
-- si el permiso CREATE SEQUENCE viene por rol. En un bloque anonimo
-- el CREATE SEQUENCE dinamico puede usar los privilegios de la sesion.

DECLARE
  PROCEDURE CREATE_SEQUENCE_IF_MISSING(
    p_sequence_name IN VARCHAR2,
    p_table_name IN VARCHAR2,
    p_pk_name IN VARCHAR2
  ) AS
    v_count NUMBER;
    v_start NUMBER := 1;
  BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_SEQUENCES
    WHERE SEQUENCE_NAME = UPPER(p_sequence_name);

    IF v_count > 0 THEN
      DBMS_OUTPUT.PUT_LINE('Sequence ' || p_sequence_name || ' ya existe.');
      RETURN;
    END IF;

    BEGIN
      EXECUTE IMMEDIATE
        'SELECT NVL(MAX(' || p_pk_name || '), 0) + 1 FROM ' || p_table_name
        INTO v_start;
    EXCEPTION
      WHEN OTHERS THEN
        v_start := 1;
    END;

    IF v_start < 1 THEN
      v_start := 1;
    END IF;

    EXECUTE IMMEDIATE
      'CREATE SEQUENCE ' || p_sequence_name ||
      ' START WITH ' || v_start ||
      ' INCREMENT BY 1 NOCACHE NOCYCLE';

    DBMS_OUTPUT.PUT_LINE('Sequence ' || p_sequence_name || ' creado.');
  END;
BEGIN
  CREATE_SEQUENCE_IF_MISSING('CLIENTES_SEQ', 'CLIENTES', 'ID');

  CREATE_SEQUENCE_IF_MISSING('EMP_CONTROL_LABORAL_SEQ', 'EMP_CONTROL_LABORAL', 'CTL_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_CUENTA_BANCARIA_SEQ', 'EMP_CUENTA_BANCARIA', 'CUE_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_DEPARTAMENTO_SEQ', 'EMP_DEPARTAMENTO', 'DEP_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_DESCUENTO_SEQ', 'EMP_DESCUENTO', 'TDS_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_EMPLEADO_SEQ', 'EMP_EMPLEADO', 'EMP_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_HORARIO_SEQ', 'EMP_HORARIO', 'HOR_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_INGRESO_SEQ', 'EMP_INGRESO', 'TIS_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_KPI_SEQ', 'EMP_KPI', 'KPI_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_KRE_SEQ', 'EMP_KPI_RESULTADO', 'KRE_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_MARCAJE_SEQ', 'EMP_MARCAJE', 'MAR_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_NOMINA_DETALLE_SEQ', 'EMP_NOMINA_DETALLE', 'DET_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_NOMINA_SEQ', 'EMP_NOMINA', 'NOM_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_PERIODO_SEQ', 'EMP_PERIODO', 'PER_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_PERMISOS_SEQ', 'EMP_PERMISOS', 'PER_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_PRESTAMO_SEQ', 'EMP_PRESTAMO', 'PRE_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_ROLES_SEQ', 'EMP_ROLES', 'ROL_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_ROL_PERMISOS_SEQ', 'EMP_ROL_PERMISOS', 'RPE_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_SUSPENSION_IGSS_SEQ', 'EMP_SUSPENSION_IGSS', 'SUS_ID');
  CREATE_SEQUENCE_IF_MISSING('EMP_USUARIO_BITACORA_SEQ', 'EMP_USUARIO_BITACORA', 'USB_ID');

  CREATE_SEQUENCE_IF_MISSING('SEQ_BITACORA', 'EMP_BITACORA', 'BIT_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_CONTRATO', 'EMP_EMPLEADO_CONTRATO', 'TCO_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_EMP_NOMINA_ASIGNACION', 'EMP_NOMINA_ASIGNACION', 'NAS_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_EMP_PRESTAMO_DETALLE', 'EMP_PRESTAMO_DETALLE', 'PDE_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_EMP_SEDE', 'EMP_SEDE', 'SED_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_EMP_USUARIO', 'EMP_USUARIO', 'USU_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_LIQUIDACION', 'EMP_LIQUIDACIONES', 'LIQ_ID');
  CREATE_SEQUENCE_IF_MISSING('SEQ_TIPO_CONTRATO', 'EMP_TIPO_CONTRATO', 'TIC_ID');
END;
/

COMMIT;
