-- Agrega datos de retencion para empleados liquidados.
-- La aplicacion marca al empleado como liquidado y calcula fecha de eliminacion
-- definitiva 3 meses despues de la salida.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EMP_LIQUIDACIONES'
    AND COLUMN_NAME = 'LIQ_FECHA_ELIMINACION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMP_LIQUIDACIONES ADD (LIQ_FECHA_ELIMINACION DATE)';
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EMP_LIQUIDACIONES'
    AND COLUMN_NAME = 'LIQ_ESTADO_RETENCION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE EMP_LIQUIDACIONES
      ADD (LIQ_ESTADO_RETENCION VARCHAR2(20) DEFAULT 'RETENIDA')
    ]';
  END IF;
END;
/

UPDATE EMP_LIQUIDACIONES
SET LIQ_FECHA_ELIMINACION = ADD_MONTHS(TRUNC(LIQ_FECHA_SALIDA), 3)
WHERE LIQ_FECHA_SALIDA IS NOT NULL
  AND LIQ_FECHA_ELIMINACION IS NULL;

UPDATE EMP_LIQUIDACIONES
SET LIQ_ESTADO_RETENCION = 'RETENIDA'
WHERE LIQ_ESTADO_RETENCION IS NULL;

COMMIT;
