DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'EMP_NOMINA_SEQ';

  IF v_count = 0 THEN
    SELECT NVL(MAX(NOM_ID), 0) + 1
    INTO v_start
    FROM EMP_NOMINA;

    EXECUTE IMMEDIATE
      'CREATE SEQUENCE EMP_NOMINA_SEQ START WITH ' || v_start ||
      ' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'EMP_NOMINA_DETALLE_SEQ';

  IF v_count = 0 THEN
    SELECT NVL(MAX(DET_ID), 0) + 1
    INTO v_start
    FROM EMP_NOMINA_DETALLE;

    EXECUTE IMMEDIATE
      'CREATE SEQUENCE EMP_NOMINA_DETALLE_SEQ START WITH ' || v_start ||
      ' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/
