DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'EMP_NOMINA_ASIGNACION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE EMP_NOMINA_ASIGNACION (
        NAS_ID NUMBER PRIMARY KEY,
        PER_ID NUMBER NOT NULL,
        EMP_ID NUMBER NOT NULL,
        TIS_ID NUMBER NULL,
        TDS_ID NUMBER NULL,
        NAS_TIPO CHAR(1) NOT NULL,
        NAS_MONTO NUMBER(12,2) NOT NULL,
        NAS_CANTIDAD NUMBER(12,2),
        NAS_REFERENCIA VARCHAR2(100),
        NAS_DESCRIPCION VARCHAR2(250),
        NAS_ESTADO CHAR(1) DEFAULT ''A'' NOT NULL,
        NAS_FECHA_CREACION DATE DEFAULT SYSDATE,
        NAS_FECHA_ACTUALIZACION DATE,
        CONSTRAINT CK_NAS_TIPO CHECK (NAS_TIPO IN (''I'', ''D'')),
        CONSTRAINT CK_NAS_MONTO CHECK (NAS_MONTO >= 0),
        CONSTRAINT CK_NAS_ESTADO CHECK (NAS_ESTADO IN (''A'', ''I'')),
        CONSTRAINT CK_NAS_CONCEPTO CHECK (
          (NAS_TIPO = ''I'' AND TIS_ID IS NOT NULL AND TDS_ID IS NULL)
          OR
          (NAS_TIPO = ''D'' AND TDS_ID IS NOT NULL AND TIS_ID IS NULL)
        ),
        CONSTRAINT FK_NAS_PER FOREIGN KEY (PER_ID) REFERENCES EMP_PERIODO(PER_ID),
        CONSTRAINT FK_NAS_EMP FOREIGN KEY (EMP_ID) REFERENCES EMP_EMPLEADO(EMP_ID),
        CONSTRAINT FK_NAS_TIS FOREIGN KEY (TIS_ID) REFERENCES EMP_INGRESO(TIS_ID),
        CONSTRAINT FK_NAS_TDS FOREIGN KEY (TDS_ID) REFERENCES EMP_DESCUENTO(TDS_ID)
      )';
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'SEQ_EMP_NOMINA_ASIGNACION';

  IF v_count = 0 THEN
    SELECT NVL(MAX(NAS_ID), 0) + 1
    INTO v_start
    FROM EMP_NOMINA_ASIGNACION;

    EXECUTE IMMEDIATE
      'CREATE SEQUENCE SEQ_EMP_NOMINA_ASIGNACION START WITH ' || v_start ||
      ' INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/
