-- Relaciona pagos de prestamo con la nomina que los desconto.
-- Esto permite rebajar saldo pendiente al aprobar nomina sin duplicar pagos.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EMP_PRESTAMO_DETALLE'
    AND COLUMN_NAME = 'PRE_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMP_PRESTAMO_DETALLE ADD (PRE_ID NUMBER)';
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EMP_PRESTAMO_DETALLE'
    AND COLUMN_NAME = 'NOM_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMP_PRESTAMO_DETALLE ADD (NOM_ID NUMBER)';
  END IF;

  SELECT COUNT(*)
  INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EMP_PRESTAMO_DETALLE'
    AND COLUMN_NAME = 'DET_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMP_PRESTAMO_DETALLE ADD (DET_ID NUMBER)';
  END IF;
END;
/

COMMIT;
